{
 "title": "Delivery Analytics",
 "tags": [
  "delivery",
  "analytics",
  "clickhouse"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Сумма стоимостей доставок",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_delivery_cost_rub FROM delivery_analytics.delivery_cost_total_view"
    }
   ]
  },
  {
   "title": "Максимальная стоимость доставки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max_delivery_cost_rub FROM delivery_analytics.delivery_cost_max_view"
    }
   ]
  },
  {
   "title": "Минимальная стоимость доставки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min_delivery_cost_rub FROM delivery_analytics.delivery_cost_min_view"
    }
   ]
  }
 ]
}