"""create parcel types and parcels tables

Revision ID: 1ce2661b0087
Revises: 
Create Date: 2026-05-04 23:44:56.868309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce2661b0087'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_session_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='parcelstatus'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('declared_value_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_cost_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['parcel_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_client_session_id'), 'parcels', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_parcels_company_id'), 'parcels', ['company_id'], unique=False)
    op.create_index(op.f('ix_parcels_type_id'), 'parcels', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_type_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_company_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_client_session_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
